app <- ShinyDriver$new("../")
app$snapshotInit("null_projLeadCombo")

# Input 'jscookie_user' was set, but doesn't have an input binding.
# Input 'jscookie_pass' was set, but doesn't have an input binding.
app$setInputs(btnNextEnv = "click")
app$setInputs(dt_sel = FALSE)
app$setInputs(closeBox_EL_JLISDAZE = "click")
app$setInputs(projLeadEnt_JLISDAZE = "CGIAR center") ##
app$setInputs(tLeadCenter_JLISDAZE = character(0))   ##
app$setInputs(lead_org_type_1_JLISDAZE = character(0))
app$setInputs(`projLeadEnt_JLISDAZE-selectized` = "")
app$setInputs(`tLeadCenter_JLISDAZE-selectized` = "")
app$setInputs(`lead_org_type_1_JLISDAZE-selectized` = "")
app$setInputs(lead_org_type_1_JLISDAZE_other = "")
app$setInputs(leadNameOther_JLISDAZE = "")
app$setInputs(expLead_JLISDAZE = "")
app$setInputs(closeBox_PERS_GXRVTWZK = "click")
app$setInputs(personnel_type_GXRVTWZK = character(0))
app$setInputs(person_affiliation_GXRVTWZK = character(0))
app$setInputs(person_center_GXRVTWZK = character(0))
app$setInputs(`personnel_type_GXRVTWZK-selectized` = "")
app$setInputs(personnel_type_GXRVTWZK_other = "")
app$setInputs(person_firstName_GXRVTWZK = "")
app$setInputs(person_lastName_GXRVTWZK = "")
app$setInputs(person_email_GXRVTWZK = "")
app$setInputs(`person_affiliation_GXRVTWZK-selectized` = "")
app$setInputs(`person_center_GXRVTWZK-selectized` = "")
app$setInputs(person_email_GXRVTWZK_other = "")
app$setInputs(person_orcid_GXRVTWZK = "")
app$setInputs(closeBox_IC_JYVQAFKF = "click")
app$setInputs(cropCommonNameInter_JYVQAFKF = character(0))
app$setInputs(cropVarietyName_JYVQAFKF = character(0))
app$setInputs(`cropCommonNameInter_JYVQAFKF-selectized` = "")
app$setInputs(cropCommonNameInter_JYVQAFKF_other = "")
app$setInputs(`cropVarietyName_JYVQAFKF-selectized` = "")
app$setInputs(intercropValue_row_crop_JYVQAFKF = "")
app$setInputs(closeBox_IC_MISFFOSR = "click")
app$setInputs(cropCommonNameInter_MISFFOSR = character(0))
app$setInputs(cropVarietyName_MISFFOSR = character(0))
app$setInputs(`cropCommonNameInter_MISFFOSR-selectized` = "")
app$setInputs(cropCommonNameInter_MISFFOSR_other = "")
app$setInputs(`cropVarietyName_MISFFOSR-selectized` = "")
app$setInputs(intercropValue_row_crop_MISFFOSR = "")
app$setInputs(btAddFullFactorial = "click")
app$setInputs(designFieldbook_agrofims_r_y = "2")
app$setInputs(`designFieldbook_agrofims_r_y-selectized` = "")
app$setInputs(closeBox_FF_HNEHLTUU = "click")
app$setInputs(btDuplicate_FF_HNEHLTUU = "click")
app$setInputs(sel_factor_HNEHLTUU_1 = character(0))
app$setInputs(sel_factor_HNEHLTUU_2 = character(0))
app$setInputs(sel_factor_HNEHLTUU_3 = character(0))
app$setInputs(numLevels_HNEHLTUU = 2)
app$setInputs(`sel_factor_HNEHLTUU_1-selectized` = "")
app$setInputs(`sel_factor_HNEHLTUU_2-selectized` = "")
app$setInputs(`sel_factor_HNEHLTUU_3-selectized` = "")
app$setInputs(closeBox_FF_SOPQQRXX = "click")
app$setInputs(btDuplicate_FF_SOPQQRXX = "click")
app$setInputs(sel_factor_SOPQQRXX_1 = character(0))
app$setInputs(sel_factor_SOPQQRXX_2 = character(0))
app$setInputs(sel_factor_SOPQQRXX_3 = character(0))
app$setInputs(numLevels_SOPQQRXX = 2)
app$setInputs(`sel_factor_SOPQQRXX_1-selectized` = "")
app$setInputs(`sel_factor_SOPQQRXX_2-selectized` = "")
app$setInputs(`sel_factor_SOPQQRXX_3-selectized` = "")
app$setInputs(irrigationevent_start_date_KXGQVHEW = character(0))
app$setInputs(irrigationevent_end_date_KXGQVHEW = character(0))
app$setInputs(closeBox_ECIR_KXGQVHEW = "click")
app$setInputs(irrigationevent_start_date_KXGQVHEW_button = "click")
app$setInputs(irrigationevent_end_date_KXGQVHEW_button = "click")
app$setInputs(irrigation_technique_KXGQVHEW = character(0))
app$setInputs(surface_irrigation_technique_KXGQVHEW = character(0))
app$setInputs(localized_irrigation_techniqueKXGQVHEW = character(0))
app$setInputs(irrigation_using_sprinkler_systems_KXGQVHEW = character(0))
app$setInputs(irrigation_source_KXGQVHEW = character(0))
app$setInputs(irrigation_source_distance_KXGQVHEWunit = character(0))
app$setInputs(irrigation_amount_KXGQVHEWunit = character(0))
app$setInputs(irrigation_source_distance_KXGQVHEW = character(0))
app$setInputs(irrigation_amount_KXGQVHEW = character(0))
app$setInputs(irrigation_notes_KXGQVHEW = "")
app$setInputs(`irrigation_technique_KXGQVHEW-selectized` = "")
app$setInputs(irrigation_technique_KXGQVHEW_other = "")
app$setInputs(`surface_irrigation_technique_KXGQVHEW-selectized` = "")
app$setInputs(surface_irrigation_technique_KXGQVHEW_other = "")
app$setInputs(`localized_irrigation_techniqueKXGQVHEW-selectized` = "")
app$setInputs(localized_irrigation_techniqueKXGQVHEW_other = "")
app$setInputs(`irrigation_using_sprinkler_systems_KXGQVHEW-selectized` = "")
app$setInputs(irrigation_using_sprinkler_systems_KXGQVHEW_other = "")
app$setInputs(`irrigation_source_KXGQVHEW-selectized` = "")
app$setInputs(irrigation_source_KXGQVHEW_other = "")
app$setInputs(`irrigation_source_distance_KXGQVHEWunit-selectized` = "")
app$setInputs(`irrigation_amount_KXGQVHEWunit-selectized` = "")
app$setInputs(weeding_start_date_OIQWUKCT = character(0))
app$setInputs(closeBox_ECWE_OIQWUKCT = "click")
app$setInputs(weeding_start_date_OIQWUKCT_button = "click")
app$setInputs(weeding_technique_OIQWUKCT = character(0))
app$setInputs(weeding_type_OIQWUKCT = character(0))
app$setInputs(weeding_traction_OIQWUKCT = character(0))
app$setInputs(weeding_notes_OIQWUKCT = "")
app$setInputs(`weeding_technique_OIQWUKCT-selectized` = "")
app$setInputs(`weeding_type_OIQWUKCT-selectized` = "")
app$setInputs(weeding_type_OIQWUKCT_other = "")
app$setInputs(`weeding_traction_OIQWUKCT-selectized` = "")
app$setInputs(weeding_traction_OIQWUKCT_other = "")
app$setInputs(input_startdate_soil_table_row_1 = character(0))
app$setInputs(input_enddate_soil_table_row_1 = character(0))
app$setInputs(input_startdate_soil_table_row_1_button = "click")
app$setInputs(input_enddate_soil_table_row_1_button = "click")
app$setInputs(select_fertilizerType_soil_table_row_1 = character(0))
app$setInputs(select_product_soil_table_row_1 = character(0))
app$setInputs(select_element_soil_table_row_1 = character(0))
app$setInputs(select_techinque_soil_table_row_1 = character(0))
app$setInputs(textArea_soil_table_row_1 = "")
app$setInputs(`select_fertilizerType_soil_table_row_1-selectized` = "")
app$setInputs(`select_product_soil_table_row_1-selectized` = "")
app$setInputs(select_product_soil_table_row_1_other = "")
app$setInputs(input_productRate_soil_table_row1 = "")
app$setInputs(`select_element_soil_table_row_1-selectized` = "")
app$setInputs(select_element_soil_table_row_1_other = "")
app$setInputs(input_elementRate_soil_table_row_1 = "")
app$setInputs(`select_techinque_soil_table_row_1-selectized` = "")
app$setInputs(select_techinque_soil_table_row_1_other = "")
app$setInputs(input_startdate_soil_table_row_2 = character(0))
app$setInputs(input_enddate_soil_table_row_2 = character(0))
app$setInputs(input_startdate_soil_table_row_2_button = "click")
app$setInputs(input_enddate_soil_table_row_2_button = "click")
app$setInputs(select_fertilizerType_soil_table_row_2 = character(0))
app$setInputs(select_product_soil_table_row_2 = character(0))
app$setInputs(select_element_soil_table_row_2 = character(0))
app$setInputs(select_techinque_soil_table_row_2 = character(0))
app$setInputs(textArea_soil_table_row_2 = "")
app$setInputs(`select_fertilizerType_soil_table_row_2-selectized` = "")
app$setInputs(`select_product_soil_table_row_2-selectized` = "")
app$setInputs(select_product_soil_table_row_2_other = "")
app$setInputs(input_productRate_soil_table_row2 = "")
app$setInputs(`select_element_soil_table_row_2-selectized` = "")
app$setInputs(select_element_soil_table_row_2_other = "")
app$setInputs(input_elementRate_soil_table_row_2 = "")
app$setInputs(`select_techinque_soil_table_row_2-selectized` = "")
app$setInputs(select_techinque_soil_table_row_2_other = "")
app$setInputs(input_startdate_soil_table_row_3 = character(0))
app$setInputs(input_enddate_soil_table_row_3 = character(0))
app$setInputs(input_startdate_soil_table_row_3_button = "click")
app$setInputs(input_enddate_soil_table_row_3_button = "click")
app$setInputs(select_fertilizerType_soil_table_row_3 = character(0))
app$setInputs(select_product_soil_table_row_3 = character(0))
app$setInputs(select_element_soil_table_row_3 = character(0))
app$setInputs(select_techinque_soil_table_row_3 = character(0))
app$setInputs(textArea_soil_table_row_3 = "")
app$setInputs(`select_fertilizerType_soil_table_row_3-selectized` = "")
app$setInputs(`select_product_soil_table_row_3-selectized` = "")
app$setInputs(select_product_soil_table_row_3_other = "")
app$setInputs(input_productRate_soil_table_row3 = "")
app$setInputs(`select_element_soil_table_row_3-selectized` = "")
app$setInputs(select_element_soil_table_row_3_other = "")
app$setInputs(input_elementRate_soil_table_row_3 = "")
app$setInputs(`select_techinque_soil_table_row_3-selectized` = "")
app$setInputs(select_techinque_soil_table_row_3_other = "")
app$setInputs(harvest_start_date_NKXKEBZJ = character(0))
app$setInputs(harvest_end_date_NKXKEBZJ = character(0))
app$setInputs(desc_harvest_titleId_NKXKEBZJ = "click")
app$setInputs(harvest_start_date_NKXKEBZJ_button = "click")
app$setInputs(harvest_end_date_NKXKEBZJ_button = "click")
app$setInputs(closeBox_HARV_NKXKEBZJ = "click")
app$setInputs(harvest_method_NKXKEBZJ = character(0))
app$setInputs(crop_component_harvested_NKXKEBZJ = character(0))
app$setInputs(crop_harvestable_area_NKXKEBZJ = character(0))
app$setInputs(crop_component_harvested_lenunit_NKXKEBZJ = character(0))
app$setInputs(crop_component_harvested_widthunit_NKXKEBZJ = character(0))
app$setInputs(crop_component_harvested_spaceunit_NKXKEBZJ = character(0))
app$setInputs(crop_component_harvested_entireunit_NKXKEBZJ = character(0))
app$setInputs(amount_harvested_unit_NKXKEBZJ = character(0))
app$setInputs(harvest_cut_height_unit_NKXKEBZJ = character(0))
app$setInputs(harvest_implement_NKXKEBZJ = character(0))
app$setInputs(harvest_traction_NKXKEBZJ = character(0))
app$setInputs(space_rows_harvested_NKXKEBZJ = character(0))
app$setInputs(amount_harvested_NKXKEBZJ = character(0))
app$setInputs(harvest_cut_height_NKXKEBZJ = character(0))
app$setInputs(harvest_notes_NKXKEBZJ = "")
app$setInputs(`harvest_method_NKXKEBZJ-selectized` = "")
app$setInputs(harvest_method_NKXKEBZJ_other = "")
app$setInputs(`crop_component_harvested_NKXKEBZJ-selectized` = "")
app$setInputs(crop_component_harvested_NKXKEBZJ_other = "")
app$setInputs(`crop_harvestable_area_NKXKEBZJ-selectized` = "")
app$setInputs(crop_component_harvested_m2_NKXKEBZJ = "")
app$setInputs(crop_component_harvested_ip_NKXKEBZJ = "")
app$setInputs(crop_component_harvested_num_NKXKEBZJ = "")
app$setInputs(crop_component_harvested_len_NKXKEBZJ = "")
app$setInputs(`crop_component_harvested_lenunit_NKXKEBZJ-selectized` = "")
app$setInputs(crop_component_harvested_width_NKXKEBZJ = "")
app$setInputs(`crop_component_harvested_widthunit_NKXKEBZJ-selectized` = "")
app$setInputs(`crop_component_harvested_spaceunit_NKXKEBZJ-selectized` = "")
app$setInputs(crop_component_harvested_entire_NKXKEBZJ = "")
app$setInputs(`crop_component_harvested_entireunit_NKXKEBZJ-selectized` = "")
app$setInputs(crop_harvestable_area_NKXKEBZJ_other = "")
app$setInputs(`amount_harvested_unit_NKXKEBZJ-selectized` = "")
app$setInputs(`harvest_cut_height_unit_NKXKEBZJ-selectized` = "")
app$setInputs(`harvest_implement_NKXKEBZJ-selectized` = "")
app$setInputs(harvest_implement_NKXKEBZJ_other = "")
app$setInputs(`harvest_traction_NKXKEBZJ-selectized` = "")
app$setInputs(harvest_traction_NKXKEBZJ_other = "")
app$setInputs(planting_start_date_1 = character(0))
app$setInputs(transplanting_start_date_1 = character(0))
app$setInputs(transplanting_end_date_1 = character(0))
app$setInputs(plantingTransplanting_titleId_1 = "click")
app$setInputs(direct_seeding_titleId_1 = "click")
app$setInputs(planting_start_date_1_button = "click")
app$setInputs(transplanting_titleId_1 = "click")
app$setInputs(transplanting_start_date_1_button = "click")
app$setInputs(transplanting_end_date_1_button = "click")
app$setInputs(seeding_environment_1 = character(0))
app$setInputs(seeding_technique_1 = character(0))
app$setInputs(seeding_implement_type_1 = character(0))
app$setInputs(seeding_traction_1 = character(0))
app$setInputs(distance_rows_unit_1 = character(0))
app$setInputs(seeding_rate_unit_1 = character(0))
app$setInputs(distance_plants_unit_1 = character(0))
app$setInputs(seeding_plant_density_unit_1 = character(0))
app$setInputs(transplanting_environment_1 = character(0))
app$setInputs(transplanting_technique_1 = character(0))
app$setInputs(trans_traction_1 = character(0))
app$setInputs(trans_distance_rows_unit_1 = character(0))
app$setInputs(trans_seeding_density_unit_1 = character(0))
app$setInputs(trans_distance_plants_unit_1 = "m")
app$setInputs(directSeeding_checkbox_1 = FALSE)
app$setInputs(transplanting_checkbox_1 = FALSE)
app$setInputs(distance_rows_1 = character(0))
app$setInputs(seeding_rate_1 = character(0))
app$setInputs(distance_plants_1 = character(0))
app$setInputs(seeding_density_number_rows_1 = character(0))
app$setInputs(seeding_plant_density_1 = character(0))
app$setInputs(age_seedling_1 = character(0))
app$setInputs(trans_distance_rows_1 = character(0))
app$setInputs(trans_seeding_density_1 = character(0))
app$setInputs(trans_num_rows_1 = character(0))
app$setInputs(trans_distance_plants_1 = character(0))
app$setInputs(direct_seeding_notes_1 = "")
app$setInputs(transplanting_density_notes_1 = "")
app$setInputs(`seeding_environment_1-selectized` = "")
app$setInputs(seeding_environment_1_other = "")
app$setInputs(`seeding_technique_1-selectized` = "")
app$setInputs(seeding_technique_1_other = "")
app$setInputs(seed_treatment_1 = "")
app$setInputs(`seeding_implement_type_1-selectized` = "")
app$setInputs(seeding_implement_type_1_other = "")
app$setInputs(`seeding_traction_1-selectized` = "")
app$setInputs(seeding_traction_1_other = "")
app$setInputs(`distance_rows_unit_1-selectized` = "")
app$setInputs(`seeding_rate_unit_1-selectized` = "")
app$setInputs(`distance_plants_unit_1-selectized` = "")
app$setInputs(`seeding_plant_density_unit_1-selectized` = "")
app$setInputs(`transplanting_environment_1-selectized` = "")
app$setInputs(transplanting_environment_1_other = "")
app$setInputs(`transplanting_technique_1-selectized` = "")
app$setInputs(transplanting_technique_1_other = "")
app$setInputs(transplanting_treatment_1 = "")
app$setInputs(`trans_traction_1-selectized` = "")
app$setInputs(trans_traction_1_other = "")
app$setInputs(`trans_distance_rows_unit_1-selectized` = "")
app$setInputs(`trans_seeding_density_unit_1-selectized` = "")
app$setInputs(`trans_distance_plants_unit_1-selectized` = "")
app$setInputs(closeModal = "click")
app$setInputs(sidebarItemExpanded = "Fieldbook")
app$setInputs(tabs = "newFieldbookAgrofims")
app$setInputs(projLeadEnt_JLISDAZE = character(0))
app$snapshotDownload("downloadData")
app$setInputs(sidebarCollapsed = TRUE)
app$setInputs(projLeadEnt_JLISDAZE = "CGIAR center")
app$snapshotDownload("downloadData")
app$setInputs(projLeadEnt_JLISDAZE = character(0))
app$setInputs(fbDesignNav = "tabPersonnel")
app$setInputs(fbDesignNav = "experiment")
app$setInputs(fbDesignNav = "tabCrop")
app$setInputs(cropCommonNameMono = "Cassava")
app$setInputs(fbDesignNav = "tabDesign")
app$setInputs(sel_factor_HNEHLTUU_1 = "Irrigation")
# Input 'selectFactor' was set, but doesn't have an input binding.
# Input 'selectFactorID' was set, but doesn't have an input binding.
# Input 'selectFactor' was set, but doesn't have an input binding.
# Input 'selectFactorID' was set, but doesn't have an input binding.
# Input 'selectFactor' was set, but doesn't have an input binding.
# Input 'selectFactorID' was set, but doesn't have an input binding.
app$setInputs(sel_factor_HNEHLTUU_2 = "Irrigation technique")
# Input 'selectFactor' was set, but doesn't have an input binding.
# Input 'selectFactorID' was set, but doesn't have an input binding.
# Input 'selectFactor' was set, but doesn't have an input binding.
# Input 'selectFactorID' was set, but doesn't have an input binding.
app$setInputs(sel_factor_HNEHLTUU_3 = "Localized irrigation technique")
# Input 'selectFactor' was set, but doesn't have an input binding.
app$setInputs(levels_HNEHLTUU = character(0))
app$setInputs(`levels_HNEHLTUU-selectized` = "")
app$setInputs(note_factor_HNEHLTUU = "")
app$setInputs(levels_HNEHLTUU = "Bubbler irrigation")
app$setInputs(levels_HNEHLTUU = c("Bubbler irrigation", "Drip irrigation"))
app$setInputs(sel_factor_SOPQQRXX_1 = "Mulch management")
# Input 'selectFactor' was set, but doesn't have an input binding.
# Input 'selectFactorID' was set, but doesn't have an input binding.
# Input 'selectFactor' was set, but doesn't have an input binding.
# Input 'selectFactorID' was set, but doesn't have an input binding.
# Input 'selectFactor' was set, but doesn't have an input binding.
# Input 'selectFactorID' was set, but doesn't have an input binding.
app$setInputs(sel_factor_SOPQQRXX_2 = "Mulch details")
# Input 'selectFactor' was set, but doesn't have an input binding.
# Input 'selectFactorID' was set, but doesn't have an input binding.
# Input 'selectFactor' was set, but doesn't have an input binding.
# Input 'selectFactorID' was set, but doesn't have an input binding.
app$setInputs(sel_factor_SOPQQRXX_3 = "Mulching implement")
# Input 'selectFactor' was set, but doesn't have an input binding.
app$setInputs(levels_SOPQQRXX = character(0))
app$setInputs(`levels_SOPQQRXX-selectized` = "")
app$setInputs(note_factor_SOPQQRXX = "")
app$setInputs(levels_SOPQQRXX = "Manual")
app$setInputs(levels_SOPQQRXX = c("Manual", "Mechanized"))
app$setInputs(fbDesign_draft_agrofims = "click")
app$setInputs(fbDesignNav = "Crop_Measurement_monocrop")
# Input 'dt_rows_current' was set, but doesn't have an input binding.
# Input 'dt_rows_all' was set, but doesn't have an input binding.
app$setInputs(fbDesignNav = "Crop_Measurement_monocrop")
# Input 'dt_rows_selected' was set, but doesn't have an input binding.
# Input 'dt_row_last_clicked' was set, but doesn't have an input binding.
# Input 'dt_cell_clicked' was set, but doesn't have an input binding.
# Input 'dt_rows_selected' was set, but doesn't have an input binding.
# Input 'dt_row_last_clicked' was set, but doesn't have an input binding.
# Input 'dt_cell_clicked' was set, but doesn't have an input binding.
# Input 'dt_rows_selected' was set, but doesn't have an input binding.
# Input 'dt_row_last_clicked' was set, but doesn't have an input binding.
# Input 'dt_cell_clicked' was set, but doesn't have an input binding.
app$setInputs(fbDesignNav = "Crop_Phenology_monocrop")
# Input 'phenoDT_rows_current' was set, but doesn't have an input binding.
# Input 'phenoDT_rows_all' was set, but doesn't have an input binding.
# Input 'phenoDT_rows_selected' was set, but doesn't have an input binding.
# Input 'phenoDT_row_last_clicked' was set, but doesn't have an input binding.
# Input 'phenoDT_cell_clicked' was set, but doesn't have an input binding.
# Input 'phenoDT_rows_selected' was set, but doesn't have an input binding.
# Input 'phenoDT_row_last_clicked' was set, but doesn't have an input binding.
# Input 'phenoDT_cell_clicked' was set, but doesn't have an input binding.
app$snapshotDownload("downloadData")
app$setInputs(fbDesignNav = "experiment")
app$setInputs(projLeadEnt_JLISDAZE = "CGIAR center")
app$snapshotDownload("downloadData")
app$setInputs(fbDesignNav = "tabSoil")
# Input 'soilDT_rows_current' was set, but doesn't have an input binding.
# Input 'soilDT_rows_all' was set, but doesn't have an input binding.
# Input 'soilDT_rows_selected' was set, but doesn't have an input binding.
# Input 'soilDT_row_last_clicked' was set, but doesn't have an input binding.
# Input 'soilDT_cell_clicked' was set, but doesn't have an input binding.
# Input 'soilDT_rows_selected' was set, but doesn't have an input binding.
# Input 'soilDT_row_last_clicked' was set, but doesn't have an input binding.
# Input 'soilDT_cell_clicked' was set, but doesn't have an input binding.
# Input 'soilDT_rows_selected' was set, but doesn't have an input binding.
# Input 'soilDT_row_last_clicked' was set, but doesn't have an input binding.
# Input 'soilDT_cell_clicked' was set, but doesn't have an input binding.
app$setInputs(fbDesignNav = "tabWeather")
app$setInputs(manualMeasurement_checkbox = TRUE)
app$setInputs(manual_measurement_titleId = "click")
# Input 'boxTitleClicked' was set, but doesn't have an input binding.
# Input 'boxTitleClickedId' was set, but doesn't have an input binding.
# Input 'weatherManualDT_rows_current' was set, but doesn't have an input binding.
# Input 'weatherManualDT_rows_all' was set, but doesn't have an input binding.
# Input 'weatherManualDT_rows_selected' was set, but doesn't have an input binding.
# Input 'weatherManualDT_row_last_clicked' was set, but doesn't have an input binding.
# Input 'weatherManualDT_cell_clicked' was set, but doesn't have an input binding.
# Input 'weatherManualDT_rows_selected' was set, but doesn't have an input binding.
# Input 'weatherManualDT_rows_selected' was set, but doesn't have an input binding.
# Input 'weatherManualDT_rows_selected' was set, but doesn't have an input binding.
# Input 'weatherManualDT_row_last_clicked' was set, but doesn't have an input binding.
# Input 'weatherManualDT_cell_clicked' was set, but doesn't have an input binding.
# Input 'weatherManualDT_rows_selected' was set, but doesn't have an input binding.
# Input 'weatherManualDT_row_last_clicked' was set, but doesn't have an input binding.
# Input 'weatherManualDT_cell_clicked' was set, but doesn't have an input binding.
app$setInputs(fbDesignNav = "Crop_Phenology_monocrop")
app$setInputs(fbDesignNav = "Crop_Measurement_monocrop")
app$setInputs(fbDesignNav = "tabAgroFeat")
app$setInputs(selectAgroFeature = "Residue management")
app$setInputs(fbDesignNav = "tabDesign")
app$setInputs(fbDesignNav = "tabCrop")
app$setInputs(fbDesignNav = "tabSite")
app$setInputs(fbDesignNav = "tabSite")
app$setInputs(fbDesignNav = "tabPersonnel")
app$setInputs(fbDesignNav = "experiment")
app$setInputs(designFieldbook_typeExperiment = "Controlled treatment trial")
app$snapshotDownload("downloadData")
app$setInputs(projLeadEnt_JLISDAZE = character(0))
app$snapshotDownload("downloadData")
app$snapshot()
