app <- ShinyDriver$new("../")
app$snapshotInit("weatherTab_Clicked_By_User")

# Input 'jscookie_user' was set, but doesn't have an input binding.
# Input 'jscookie_pass' was set, but doesn't have an input binding.
app$setInputs(btnNextEnv = "click")
app$setInputs(dt_sel = FALSE)
app$setInputs(irrigationevent_start_date_FLBESLKG = character(0))
app$setInputs(irrigationevent_end_date_FLBESLKG = character(0))
app$setInputs(closeBox_ECIR_FLBESLKG = "click")
app$setInputs(irrigationevent_start_date_FLBESLKG_button = "click")
app$setInputs(irrigationevent_end_date_FLBESLKG_button = "click")
app$setInputs(irrigation_technique_FLBESLKG = character(0))
app$setInputs(surface_irrigation_technique_FLBESLKG = character(0))
app$setInputs(localized_irrigation_techniqueFLBESLKG = character(0))
app$setInputs(irrigation_using_sprinkler_systems_FLBESLKG = character(0))
app$setInputs(irrigation_source_FLBESLKG = character(0))
app$setInputs(irrigation_source_distance_FLBESLKGunit = character(0))
app$setInputs(irrigation_amount_FLBESLKGunit = character(0))
app$setInputs(irrigation_source_distance_FLBESLKG = character(0))
app$setInputs(irrigation_amount_FLBESLKG = character(0))
app$setInputs(irrigation_notes_FLBESLKG = "")
app$setInputs(`irrigation_technique_FLBESLKG-selectized` = "")
app$setInputs(irrigation_technique_FLBESLKG_other = "")
app$setInputs(`surface_irrigation_technique_FLBESLKG-selectized` = "")
app$setInputs(surface_irrigation_technique_FLBESLKG_other = "")
app$setInputs(`localized_irrigation_techniqueFLBESLKG-selectized` = "")
app$setInputs(localized_irrigation_techniqueFLBESLKG_other = "")
app$setInputs(`irrigation_using_sprinkler_systems_FLBESLKG-selectized` = "")
app$setInputs(irrigation_using_sprinkler_systems_FLBESLKG_other = "")
app$setInputs(`irrigation_source_FLBESLKG-selectized` = "")
app$setInputs(irrigation_source_FLBESLKG_other = "")
app$setInputs(`irrigation_source_distance_FLBESLKGunit-selectized` = "")
app$setInputs(`irrigation_amount_FLBESLKGunit-selectized` = "")
app$setInputs(weeding_start_date_AYWDXJCM = character(0))
app$setInputs(closeBox_ECWE_AYWDXJCM = "click")
app$setInputs(weeding_start_date_AYWDXJCM_button = "click")
app$setInputs(weeding_technique_AYWDXJCM = character(0))
app$setInputs(weeding_type_AYWDXJCM = character(0))
app$setInputs(weeding_traction_AYWDXJCM = character(0))
app$setInputs(weeding_notes_AYWDXJCM = "")
app$setInputs(`weeding_technique_AYWDXJCM-selectized` = "")
app$setInputs(`weeding_type_AYWDXJCM-selectized` = "")
app$setInputs(weeding_type_AYWDXJCM_other = "")
app$setInputs(`weeding_traction_AYWDXJCM-selectized` = "")
app$setInputs(weeding_traction_AYWDXJCM_other = "")
app$setInputs(input_startdate_soil_table_row_1 = character(0))
app$setInputs(input_enddate_soil_table_row_1 = character(0))
app$setInputs(input_startdate_soil_table_row_1_button = "click")
app$setInputs(input_enddate_soil_table_row_1_button = "click")
app$setInputs(select_fertilizerType_soil_table_row_1 = character(0))
app$setInputs(select_product_soil_table_row_1 = character(0))
app$setInputs(select_element_soil_table_row_1 = character(0))
app$setInputs(select_techinque_soil_table_row_1 = character(0))
app$setInputs(textArea_soil_table_row_1 = "")
app$setInputs(`select_fertilizerType_soil_table_row_1-selectized` = "")
app$setInputs(`select_product_soil_table_row_1-selectized` = "")
app$setInputs(select_product_soil_table_row_1_other = "")
app$setInputs(input_productRate_soil_table_row1 = "")
app$setInputs(`select_element_soil_table_row_1-selectized` = "")
app$setInputs(select_element_soil_table_row_1_other = "")
app$setInputs(input_elementRate_soil_table_row_1 = "")
app$setInputs(`select_techinque_soil_table_row_1-selectized` = "")
app$setInputs(select_techinque_soil_table_row_1_other = "")
app$setInputs(input_startdate_soil_table_row_2 = character(0))
app$setInputs(input_enddate_soil_table_row_2 = character(0))
app$setInputs(input_startdate_soil_table_row_2_button = "click")
app$setInputs(input_enddate_soil_table_row_2_button = "click")
app$setInputs(select_fertilizerType_soil_table_row_2 = character(0))
app$setInputs(select_product_soil_table_row_2 = character(0))
app$setInputs(select_element_soil_table_row_2 = character(0))
app$setInputs(select_techinque_soil_table_row_2 = character(0))
app$setInputs(textArea_soil_table_row_2 = "")
app$setInputs(`select_fertilizerType_soil_table_row_2-selectized` = "")
app$setInputs(`select_product_soil_table_row_2-selectized` = "")
app$setInputs(select_product_soil_table_row_2_other = "")
app$setInputs(input_productRate_soil_table_row2 = "")
app$setInputs(`select_element_soil_table_row_2-selectized` = "")
app$setInputs(select_element_soil_table_row_2_other = "")
app$setInputs(input_elementRate_soil_table_row_2 = "")
app$setInputs(`select_techinque_soil_table_row_2-selectized` = "")
app$setInputs(select_techinque_soil_table_row_2_other = "")
app$setInputs(input_startdate_soil_table_row_3 = character(0))
app$setInputs(input_enddate_soil_table_row_3 = character(0))
app$setInputs(input_startdate_soil_table_row_3_button = "click")
app$setInputs(input_enddate_soil_table_row_3_button = "click")
app$setInputs(select_fertilizerType_soil_table_row_3 = character(0))
app$setInputs(select_product_soil_table_row_3 = character(0))
app$setInputs(select_element_soil_table_row_3 = character(0))
app$setInputs(select_techinque_soil_table_row_3 = character(0))
app$setInputs(textArea_soil_table_row_3 = "")
app$setInputs(`select_fertilizerType_soil_table_row_3-selectized` = "")
app$setInputs(`select_product_soil_table_row_3-selectized` = "")
app$setInputs(select_product_soil_table_row_3_other = "")
app$setInputs(input_productRate_soil_table_row3 = "")
app$setInputs(`select_element_soil_table_row_3-selectized` = "")
app$setInputs(select_element_soil_table_row_3_other = "")
app$setInputs(input_elementRate_soil_table_row_3 = "")
app$setInputs(`select_techinque_soil_table_row_3-selectized` = "")
app$setInputs(select_techinque_soil_table_row_3_other = "")
app$setInputs(harvest_start_date_HTDLBVZS = character(0))
app$setInputs(harvest_end_date_HTDLBVZS = character(0))
app$setInputs(desc_harvest_titleId_HTDLBVZS = "click")
app$setInputs(harvest_start_date_HTDLBVZS_button = "click")
app$setInputs(harvest_end_date_HTDLBVZS_button = "click")
app$setInputs(closeBox_HARV_HTDLBVZS = "click")
app$setInputs(harvest_method_HTDLBVZS = character(0))
app$setInputs(crop_component_harvested_HTDLBVZS = character(0))
app$setInputs(crop_harvestable_area_HTDLBVZS = character(0))
app$setInputs(crop_component_harvested_lenunit_HTDLBVZS = character(0))
app$setInputs(crop_component_harvested_widthunit_HTDLBVZS = character(0))
app$setInputs(crop_component_harvested_spaceunit_HTDLBVZS = character(0))
app$setInputs(crop_component_harvested_entireunit_HTDLBVZS = character(0))
app$setInputs(amount_harvested_unit_HTDLBVZS = character(0))
app$setInputs(harvest_cut_height_unit_HTDLBVZS = character(0))
app$setInputs(harvest_implement_HTDLBVZS = character(0))
app$setInputs(harvest_traction_HTDLBVZS = character(0))
app$setInputs(space_rows_harvested_HTDLBVZS = character(0))
app$setInputs(amount_harvested_HTDLBVZS = character(0))
app$setInputs(harvest_cut_height_HTDLBVZS = character(0))
app$setInputs(harvest_notes_HTDLBVZS = "")
app$setInputs(`harvest_method_HTDLBVZS-selectized` = "")
app$setInputs(harvest_method_HTDLBVZS_other = "")
app$setInputs(`crop_component_harvested_HTDLBVZS-selectized` = "")
app$setInputs(crop_component_harvested_HTDLBVZS_other = "")
app$setInputs(`crop_harvestable_area_HTDLBVZS-selectized` = "")
app$setInputs(crop_component_harvested_m2_HTDLBVZS = "")
app$setInputs(crop_component_harvested_ip_HTDLBVZS = "")
app$setInputs(crop_component_harvested_num_HTDLBVZS = "")
app$setInputs(crop_component_harvested_len_HTDLBVZS = "")
app$setInputs(`crop_component_harvested_lenunit_HTDLBVZS-selectized` = "")
app$setInputs(crop_component_harvested_width_HTDLBVZS = "")
app$setInputs(`crop_component_harvested_widthunit_HTDLBVZS-selectized` = "")
app$setInputs(`crop_component_harvested_spaceunit_HTDLBVZS-selectized` = "")
app$setInputs(crop_component_harvested_entire_HTDLBVZS = "")
app$setInputs(`crop_component_harvested_entireunit_HTDLBVZS-selectized` = "")
app$setInputs(crop_harvestable_area_HTDLBVZS_other = "")
app$setInputs(`amount_harvested_unit_HTDLBVZS-selectized` = "")
app$setInputs(`harvest_cut_height_unit_HTDLBVZS-selectized` = "")
app$setInputs(`harvest_implement_HTDLBVZS-selectized` = "")
app$setInputs(harvest_implement_HTDLBVZS_other = "")
app$setInputs(`harvest_traction_HTDLBVZS-selectized` = "")
app$setInputs(harvest_traction_HTDLBVZS_other = "")
app$setInputs(planting_start_date_1 = character(0))
app$setInputs(transplanting_start_date_1 = character(0))
app$setInputs(transplanting_end_date_1 = character(0))
app$setInputs(plantingTransplanting_titleId_1 = "click")
app$setInputs(direct_seeding_titleId_1 = "click")
app$setInputs(planting_start_date_1_button = "click")
app$setInputs(transplanting_titleId_1 = "click")
app$setInputs(transplanting_start_date_1_button = "click")
app$setInputs(transplanting_end_date_1_button = "click")
app$setInputs(seeding_environment_1 = character(0))
app$setInputs(seeding_technique_1 = character(0))
app$setInputs(seeding_implement_type_1 = character(0))
app$setInputs(seeding_traction_1 = character(0))
app$setInputs(distance_rows_unit_1 = character(0))
app$setInputs(seeding_rate_unit_1 = character(0))
app$setInputs(distance_plants_unit_1 = character(0))
app$setInputs(seeding_plant_density_unit_1 = character(0))
app$setInputs(transplanting_environment_1 = character(0))
app$setInputs(transplanting_technique_1 = character(0))
app$setInputs(trans_traction_1 = character(0))
app$setInputs(trans_distance_rows_unit_1 = character(0))
app$setInputs(trans_seeding_density_unit_1 = character(0))
app$setInputs(trans_distance_plants_unit_1 = "m")
app$setInputs(directSeeding_checkbox_1 = FALSE)
app$setInputs(transplanting_checkbox_1 = FALSE)
app$setInputs(distance_rows_1 = character(0))
app$setInputs(seeding_rate_1 = character(0))
app$setInputs(distance_plants_1 = character(0))
app$setInputs(seeding_density_number_rows_1 = character(0))
app$setInputs(seeding_plant_density_1 = character(0))
app$setInputs(age_seedling_1 = character(0))
app$setInputs(trans_distance_rows_1 = character(0))
app$setInputs(trans_seeding_density_1 = character(0))
app$setInputs(trans_num_rows_1 = character(0))
app$setInputs(trans_distance_plants_1 = character(0))
app$setInputs(direct_seeding_notes_1 = "")
app$setInputs(transplanting_density_notes_1 = "")
app$setInputs(`seeding_environment_1-selectized` = "")
app$setInputs(seeding_environment_1_other = "")
app$setInputs(`seeding_technique_1-selectized` = "")
app$setInputs(seeding_technique_1_other = "")
app$setInputs(seed_treatment_1 = "")
app$setInputs(`seeding_implement_type_1-selectized` = "")
app$setInputs(seeding_implement_type_1_other = "")
app$setInputs(`seeding_traction_1-selectized` = "")
app$setInputs(seeding_traction_1_other = "")
app$setInputs(`distance_rows_unit_1-selectized` = "")
app$setInputs(`seeding_rate_unit_1-selectized` = "")
app$setInputs(`distance_plants_unit_1-selectized` = "")
app$setInputs(`seeding_plant_density_unit_1-selectized` = "")
app$setInputs(`transplanting_environment_1-selectized` = "")
app$setInputs(transplanting_environment_1_other = "")
app$setInputs(`transplanting_technique_1-selectized` = "")
app$setInputs(transplanting_technique_1_other = "")
app$setInputs(transplanting_treatment_1 = "")
app$setInputs(`trans_traction_1-selectized` = "")
app$setInputs(trans_traction_1_other = "")
app$setInputs(`trans_distance_rows_unit_1-selectized` = "")
app$setInputs(`trans_seeding_density_unit_1-selectized` = "")
app$setInputs(`trans_distance_plants_unit_1-selectized` = "")
app$setInputs(closeModal = "click")
app$setInputs(sidebarItemExpanded = "Fieldbook")
app$setInputs(tabs = "newFieldbookAgrofims")
app$setInputs(projLeadEnt_WIEBXDNZ = "Other")
app$setInputs(lead_org_type_1_WIEBXDNZ = "Other")
app$setInputs(lead_org_type_1_WIEBXDNZ_other = "other")
app$setInputs(leadNameOther_WIEBXDNZ = "Experiment, lead organization name")
app$setInputs(expLead_WIEBXDNZ = "Experiment lead person / Primary Investigator")
app$setInputs(fbDesignNav = "tabPersonnel")
app$setInputs(fbDesignNav = "tabSite")
app$setInputs(fbDesignNav = "tabCrop")
app$setInputs(cropCommonNameMono = "Cassava")
app$setInputs(fbDesignNav = "tabDesign")
app$setInputs(sel_factor_KSMHYBOH_1 = "Harvest")
# Input 'selectFactor' was set, but doesn't have an input binding.
# Input 'selectFactorID' was set, but doesn't have an input binding.
# Input 'selectFactor' was set, but doesn't have an input binding.
# Input 'selectFactorID' was set, but doesn't have an input binding.
# Input 'selectFactor' was set, but doesn't have an input binding.
# Input 'selectFactorID' was set, but doesn't have an input binding.
app$setInputs(sel_factor_YFRAMZWX_1 = "Irrigation")
# Input 'selectFactor' was set, but doesn't have an input binding.
# Input 'selectFactorID' was set, but doesn't have an input binding.
# Input 'selectFactor' was set, but doesn't have an input binding.
# Input 'selectFactorID' was set, but doesn't have an input binding.
# Input 'selectFactor' was set, but doesn't have an input binding.
# Input 'selectFactorID' was set, but doesn't have an input binding.
app$setInputs(sel_factor_KSMHYBOH_2 = "Harvest implement")
# Input 'selectFactor' was set, but doesn't have an input binding.
# Input 'selectFactorID' was set, but doesn't have an input binding.
# Input 'selectFactor' was set, but doesn't have an input binding.
# Input 'selectFactorID' was set, but doesn't have an input binding.
app$setInputs(sel_factor_KSMHYBOH_3 = "Type")
# Input 'selectFactor' was set, but doesn't have an input binding.
app$setInputs(levels_KSMHYBOH = character(0))
app$setInputs(`levels_KSMHYBOH-selectized` = "")
app$setInputs(note_factor_KSMHYBOH = "")
app$setInputs(levels_KSMHYBOH = "Baler")
app$setInputs(levels_KSMHYBOH = c("Baler", "Chopper"))
app$setInputs(sel_factor_YFRAMZWX_2 = "Irrigation technique")
# Input 'selectFactor' was set, but doesn't have an input binding.
# Input 'selectFactorID' was set, but doesn't have an input binding.
# Input 'selectFactor' was set, but doesn't have an input binding.
# Input 'selectFactorID' was set, but doesn't have an input binding.
app$setInputs(sel_factor_YFRAMZWX_3 = "Localized irrigation technique")
# Input 'selectFactor' was set, but doesn't have an input binding.
app$setInputs(levels_YFRAMZWX = character(0))
app$setInputs(`levels_YFRAMZWX-selectized` = "")
app$setInputs(note_factor_YFRAMZWX = "")
app$setInputs(levels_YFRAMZWX = "Bubbler irrigation")
app$setInputs(levels_YFRAMZWX = c("Bubbler irrigation", "Drip irrigation"))
app$setInputs(fbDesignNav = "tabAgroFeat")
app$setInputs(fbDesignNav = "Crop_Measurement_monocrop")
# Input 'dt_rows_current' was set, but doesn't have an input binding.
# Input 'dt_rows_all' was set, but doesn't have an input binding.
# Input 'dt_rows_selected' was set, but doesn't have an input binding.
# Input 'dt_row_last_clicked' was set, but doesn't have an input binding.
# Input 'dt_cell_clicked' was set, but doesn't have an input binding.
# Input 'dt_rows_selected' was set, but doesn't have an input binding.
# Input 'dt_row_last_clicked' was set, but doesn't have an input binding.
# Input 'dt_cell_clicked' was set, but doesn't have an input binding.
# Input 'dt_rows_selected' was set, but doesn't have an input binding.
# Input 'dt_row_last_clicked' was set, but doesn't have an input binding.
# Input 'dt_cell_clicked' was set, but doesn't have an input binding.
# Input 'dt_rows_selected' was set, but doesn't have an input binding.
# Input 'dt_row_last_clicked' was set, but doesn't have an input binding.
# Input 'dt_cell_clicked' was set, but doesn't have an input binding.
app$setInputs(fbDesignNav = "Crop_Phenology_monocrop")
# Input 'phenoDT_rows_current' was set, but doesn't have an input binding.
# Input 'phenoDT_rows_all' was set, but doesn't have an input binding.
# Input 'phenoDT_rows_selected' was set, but doesn't have an input binding.
# Input 'phenoDT_row_last_clicked' was set, but doesn't have an input binding.
# Input 'phenoDT_cell_clicked' was set, but doesn't have an input binding.
# Input 'phenoDT_rows_selected' was set, but doesn't have an input binding.
# Input 'phenoDT_row_last_clicked' was set, but doesn't have an input binding.
# Input 'phenoDT_cell_clicked' was set, but doesn't have an input binding.
# Input 'phenoDT_rows_selected' was set, but doesn't have an input binding.
# Input 'phenoDT_row_last_clicked' was set, but doesn't have an input binding.
# Input 'phenoDT_cell_clicked' was set, but doesn't have an input binding.
# Input 'phenoDT_rows_selected' was set, but doesn't have an input binding.
# Input 'phenoDT_row_last_clicked' was set, but doesn't have an input binding.
# Input 'phenoDT_cell_clicked' was set, but doesn't have an input binding.
# Input 'phenoDT_rows_selected' was set, but doesn't have an input binding.
# Input 'phenoDT_row_last_clicked' was set, but doesn't have an input binding.
# Input 'phenoDT_cell_clicked' was set, but doesn't have an input binding.
app$setInputs(fbDesignNav = "experiment")
app$snapshotDownload("downloadData")
app$setInputs(fbDesignNav = "Crop_Phenology_monocrop")
app$snapshotDownload("downloadData")
app$setInputs(fbDesignNav = "tabWeather")
app$snapshotDownload("downloadData")
app$setInputs(fbDesignNav = "experiment")
